### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by subinoy7**
Creating a tabular view for all the contributors

### CODE REVIEW

**Comment by subinoy7** [comment]
@adeora7  can you please verify.

**Comment by adeora7** [comment]
@subinoy7 can you please include the newly added names also. There was a pending PR for the same so I had to see that first.
It looks awesome !!

**Comment by subinoy7** [comment]
@adeora7 Thanks for the feedback and surely I will add the new contributors.

**Comment by subinoy7** [comment]
@adeora7 I have updated the new contributors list

**Pull request merged**
