### PR TITLE
Fix Issue #45

### PR DESCRIPTION
**Pull request by samyok**
> If 403 error returned when calling API, we should probably handle this better.
>
> Suggestion:
> Don't change any UI unless a ~200 is returned successfully.

Has a switch so others can add more errors as they come up.

### CODE REVIEW

**Comment by lmcjt37** [comment]
Unsure that there is a need to add JQuery - thoughts @adeora7 ?

**Comment by adeora7** [comment]
Sorry for late reply @lmcjt37  and yeah almost all of the code is custom so even I think there is no need to add jquery now. If @Nepaltechguy2  you are still solving it, please make the changes.

**Comment by Nepaltechguy2** [comment]
Ok but I might not have time within the next week or so :/

**Comment by Nepaltechguy2** [comment]
Oops didn’t mean to close sorry

**Comment by samyok** [comment]
Ok but I might not have time within the next week or so :/

**Comment by adeora7** [comment]
@Nepaltechguy2 no problem. Anyway this extension will be active again next year only when hacktoberfest comes.

**Pull request closed without merging**
